import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Musicast",
  description: "Generated by Dhruv Negi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
            <div className="relative w-full flex items-center justify-center ">
              <Navbar />
            </div>
          {children}
        </ThemeProvider>
      </body> 
    </html>
  );
}
